package cn.edu.xmu.activity.mapper;

import cn.edu.xmu.activity.model.po.PreSalePo;
import cn.edu.xmu.activity.model.po.PreSalePoExample;
import java.util.List;

public interface PreSalePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int insert(PreSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int insertSelective(PreSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    List<PreSalePo> selectByExample(PreSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    PreSalePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PreSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table presale_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PreSalePo record);
}